version: '3.4'

services:
  covidvaccineschedulesqueryapi:
    image: ${DOCKER_REGISTRY-}covidvaccineschedulesqueryapi
    build:
      context: .
      dockerfile: src/Dockerfile
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo

  redis:
    image: redis

  redisinsight:
    image: redislabs/redisinsight
    depends_on:
      - redis